import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function world(n=40){const c=vm.createContext({console,Math,Set,Map,ST:{PLAY:3},state:3,playerTeam:'moldavia',player:{dead:false,group:{position:{x:0,z:0}}},curOrder:'follow',gameTime:0,pendingAlerts:[],DOCTRINE:{bg:.05,def:.4},ZN:4,SCOPES:[1,.5,.1],cmdScopeIdx:0,Snd:{tone(){}},spawnRing(){},killFeedMsg(){},freeGoal:(x,z)=>({x,z}),clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),rand:(a,b)=>(a+b)/2,eqNear(){},zoneCenter:i=>({x:(i%4)*100,z:Math.floor(i/4)*100,gx:i%4,gz:Math.floor(i/4)}),hostileF:(a,b)=>a!==b});c.zones=Array.from({length:16},(_,i)=>({owner:i<2?'moldavia':'enemy'}));c.entities=Array.from({length:n},(_,i)=>({hp:100+i,dmg:10,dead:false,team:'moldavia',kind:'curtean',group:{position:{x:i%8,z:0}},order:'follow'}));for(const f of ['queries','commands'])vm.runInContext(readFileSync('src/groups/'+f+'.js','utf8'),c);return c;}
const run=(c,s)=>vm.runInContext(s,c);
test('unlimited player units form unlimited eight-person formations',()=>{const c=world(1200);assert.equal(run(c,'formGroups();GROUPS.reduce((n,g)=>n+g.members.length,0)'),1200);assert.equal(run(c,'GROUPS.length'),150);assert.ok(run(c,'GROUPS.every(g=>g.members.length<=8&&g.task)'));});
test('reforming preserves living group identities and excludes old campaigns',()=>{const c=world();assert.ok(run(c,'formGroups();var first=GROUPS[0].id;formGroups();GROUPS[0].id===first'));c.entities=[];assert.equal(run(c,'formGroups();GROUPS.length'),0);});
test('scope affects exactly selected units, even within an existing group',()=>{const c=world(37);assert.equal(run(c,"formGroups();cmdScopeIdx=2;issueOrder('halt')"),4);assert.equal(run(c,"entities.filter(e=>e.order==='halt').length"),4);assert.equal(run(c,"entities.filter(e=>e.order==='follow').length"),33);assert.equal(run(c,'new Set(GROUPS.flatMap(g=>g.members)).size'),37);});
test('doctrine uses exact global quotas and weakest units defend',()=>{const c=world();run(c,"assignTasks('defend',null,null)");assert.equal(run(c,"entities.filter(e=>e.role==='bodyguard').length"),2);assert.equal(run(c,"entities.filter(e=>e.role==='defender').length"),16);assert.equal(run(c,"entities.filter(e=>e.role==='attacker').length"),22);assert.ok(run(c,"Math.max(...entities.filter(e=>e.role==='defender').map(e=>e.hp))<Math.min(...entities.filter(e=>e.role==='attacker').map(e=>e.hp))"));assert.equal(run(c,"new Set(entities.filter(e=>e.role==='defender').map(e=>e.post.x)).size"),2);});
test('zero guard/defend doctrine creates no forced guard group',()=>{const c=world();c.DOCTRINE={bg:0,def:0};assert.ok(run(c,"assignTasks('defend',null,null);entities.every(e=>e.role==='attacker')"));});
test('area command preserves unselected orders and creates unique membership',()=>{const c=world(39);assert.equal(run(c,'formGroups();cmdScopeIdx=1;issueAreaOrder(55,60)'),20);assert.equal(run(c,"entities.filter(e=>e.order==='area'&&e.post.x===55).length"),20);assert.equal(run(c,'GROUPS.flatMap(g=>g.members).length'),39);});
test('new recruits inherit the active order without erasing existing tasks',()=>{const c=world(8);assert.ok(run(c,"curOrder='attack';formGroups();GROUPS.every(g=>g.task==='attack'&&g.atkTarget!==null)"));});
test('attackers spread across distinct frontier targets before sharing',()=>{const c=world(32);assert.equal(run(c,"assignTasks('attack');new Set(GROUPS.map(g=>g.atkTarget)).size"),3);});
test('reinforcement reservations prevent forwarding the same group twice',()=>{const c=world(48);run(c,"assignTasks('attack');GROUPS.forEach((g,i)=>g.members.forEach(m=>m.group.position.x=i*200));");c.eqNear=(x,z,r,fn)=>{if(x===0&&r===80)for(let i=0;i<25;i++)fn({team:'enemy',kind:'soldier'});};run(c,'groupT=0;groupThink(2.2)');assert.equal(run(c,'GROUPS.filter(g=>g.supporting===GROUPS[0].id).length'),3);run(c,'groupT=0;groupThink(2.2)');assert.equal(run(c,'GROUPS.filter(g=>g.supporting===GROUPS[0].id).length'),3);c.eqNear=()=>{};run(c,'groupT=0;groupThink(2.2)');assert.equal(run(c,'GROUPS.filter(g=>g.supporting).length'),0);});
