import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function sandbox(){const c=vm.createContext({console,Math,Set,Map,performance,WORLD:{half:200},window:{}});vm.runInContext(readFileSync('src/system/helpers.js','utf8').replace(/^var \$.*\n.*window.THREE.*\n/m,''),c);for(const f of ['collision','pathfinding'])vm.runInContext(readFileSync('src/navigation/'+f+'.js','utf8'),c);return c;}
function run(c,code){return vm.runInContext(code,c);}
test('exact collision blocks thin walls and diagonal corner cutting',()=>{const c=sandbox();assert.equal(run(c,'addCollider(-0.1,-8,0.1,8);segmentClear(-15,0,15,0,0.65)'),false);assert.equal(run(c,'segmentClear(-15,12,15,12,0.65)'),true);assert.equal(run(c,'segmentClear(-1,8.5,1,8.5,0.65)'),false);});
test('swept motion cannot tunnel at high speed and slides along walls',()=>{const c=sandbox();assert.ok(run(c,'addCollider(0,-20,0.2,20);var p={x:-10,z:0};moveWithCollision(p,30,10,0.5);p.x<0 && p.z>5 && !insideSolid(p.x,p.z,0.5)'));});
test('free spawn search escapes the center of a large building',()=>{const c=sandbox();assert.ok(run(c,'addCollider(-30,-30,30,30);var p=findFreeSpot(0,0,0.5);!insideSolid(p.x,p.z,0.5)'));});
test('A* routes around a building with exact-safe smoothed segments',()=>{const c=sandbox();assert.ok(run(c,`addCollider(-8,-24,8,24);var nav=createNavigator({half:150,cell:4,blocked:(x,z)=>insideSolid(x,z,.65),clear:(a,b,c,d)=>segmentClear(a,b,c,d,.65)});var path=nav.find(-30,0,30,0);var previous={x:-30,z:0};path&&path.length>1&&path.every(p=>{var ok=segmentClear(previous.x,previous.z,p.x,p.z,.65);previous=p;return ok;})`));});
test('repeated A* searches do not inherit stale closed flags',()=>{const c=sandbox();assert.ok(run(c,`addCollider(-8,-24,8,24);var nav=createNavigator({half:150,cell:4,blocked:(x,z)=>insideSolid(x,z,.65),clear:(a,b,c,d)=>segmentClear(a,b,c,d,.65)});Array.from({length:20},(_,i)=>nav.find(-30,i-10,30,10-i)).every(Boolean)`));});
test('road discounts apply to road nodes and preserve safe routes',()=>{const c=sandbox();assert.ok(run(c,`addCollider(-4,-30,4,30);var nav=createNavigator({half:150,cell:4,blocked:(x,z)=>insideSolid(x,z,.65),clear:(a,b,c,d)=>segmentClear(a,b,c,d,.65),road:(x,z)=>z>0});var path=nav.find(-45,0,45,0);path&&path.some(p=>p.z>30)&&!path.some(p=>p.z< -30)`));});
test('enclosed target returns failure, never a wall-crossing route',()=>{const c=sandbox();assert.equal(run(c,`addCollider(-10,-10,10,-8);addCollider(-10,8,10,10);addCollider(-10,-10,-8,10);addCollider(8,-10,10,10);var nav=createNavigator({half:80,cell:4,maxNodes:3000,blocked:(x,z)=>insideSolid(x,z,.65),clear:(a,b,c,d)=>segmentClear(a,b,c,d,.65)});nav.find(-40,0,0,0)`),null);});
test('navigation invalidates cached geometry after adding an obstacle',()=>{const c=sandbox();assert.ok(run(c,`var first=navFind(-40,0,40,0);addCollider(-4,-20,4,20);var second=navFind(-40,0,40,0);first.length===1&&second.length>1`));});
test('fine local navigation handles narrow gates and short-distance obstacles',()=>{const c=sandbox();assert.ok(run(c,`addCollider(-1,-60,1,0);addCollider(-1,4,1,60);var path=navFind(-12,2,12,8);var previous={x:-12,z:2};path&&path.every(p=>{var ok=navLos(previous.x,previous.z,p.x,p.z);previous=p;return ok;})`));});
test('invalid coordinates fail safely',()=>{const c=sandbox();assert.equal(run(c,'navFind(NaN,0,1,2)'),null);assert.equal(run(c,'navFind(0,0,9999,2)'),null);});
